server:
  address: 0.0.0.0
  port: 4060

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 1024MB
      max-file-size: 1024MB
  datasource:
    url: jdbc:mysql://47.115.214.246:3306/luce?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ichirinko
    password: Laodou123456+1s
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ichirinko.luce.model


springdoc:
  api-docs:
    enabled: on
  swagger-ui:
    path: /swagger.html
    enabled: true

server-file:
  src: /home/ichirinko/luce/videos/
